# WayWeather config
# ip_loc enables/disables autolocation through ip address
# latitide, longitude, city and country must be set when ip_loc is false
# units can be either "imp" or "met" (imperial and metric)

[wayweather]
ip_loc = false
latitude = 33.576138
longitude = -117.725812
city = "Aliso Viejo"
country = "USA"
units = "imp"
