wallpaper {
  monitor = DP-3
  path = ~/zelda_backgrounds/zelda_wp1.jpg
  fit_mode = cover
}
wallpaper {
  monitor = DP-2
  path = ~/zelda_backgrounds/zelda_wp2.jpg
  fit_mode = cover
}
wallpaper {
  monitor = DP-1
  path = ~/zelda_backgrounds/zelda_wp3.jpg
  fit_mode = cover
}
wallpaper {
  monitor = HDMI-A-1
  path = ~/zelda_backgrounds/zelda_wp4.jpg
  fit_mode = cover
}
splash = false
